// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy0TvtBomQar5SUTAiC5Tpg6YhDNwEpHI',
    appId: '1:250130658777:web:ea05fd3370c50e5d1fd5c8',
    messagingSenderId: '250130658777',
    projectId: 'subirarchivo-b34c6',
    authDomain: 'subirarchivo-b34c6.firebaseapp.com',
    databaseURL: 'https://subirarchivo-b34c6-default-rtdb.firebaseio.com',
    storageBucket: 'subirarchivo-b34c6.appspot.com',
    measurementId: 'G-CVEFVHNCGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_TYL4p8v1lZxm2KKbbggasHXD1H_hqlE',
    appId: '1:250130658777:android:dceccce10c2590941fd5c8',
    messagingSenderId: '250130658777',
    projectId: 'subirarchivo-b34c6',
    databaseURL: 'https://subirarchivo-b34c6-default-rtdb.firebaseio.com',
    storageBucket: 'subirarchivo-b34c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjIS0kgrYQH6Vh-FgxmJK3Zzeh_kIQYho',
    appId: '1:250130658777:ios:0ed4416efbe626141fd5c8',
    messagingSenderId: '250130658777',
    projectId: 'subirarchivo-b34c6',
    databaseURL: 'https://subirarchivo-b34c6-default-rtdb.firebaseio.com',
    storageBucket: 'subirarchivo-b34c6.appspot.com',
    iosBundleId: 'com.cristianosky.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjIS0kgrYQH6Vh-FgxmJK3Zzeh_kIQYho',
    appId: '1:250130658777:ios:0abba2ee06ee7f341fd5c8',
    messagingSenderId: '250130658777',
    projectId: 'subirarchivo-b34c6',
    databaseURL: 'https://subirarchivo-b34c6-default-rtdb.firebaseio.com',
    storageBucket: 'subirarchivo-b34c6.appspot.com',
    iosBundleId: 'com.cristianosky.app.RunnerTests',
  );
}
